### PR TITLE
Fix docs - platform_service_list examples

### PR DESCRIPTION
**Pull request by NoahCallaway**
## Describe your changes

Updating `harness_platform_service_list` docs examples to use the correct data source name. 

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`
- gitleaks: `trigger gitleaks`

### CODE REVIEW

**Review by namantalaycha10 — APPROVED** [review]

**Comment by namantalaycha10** [comment]
trigger gitleaks

**Comment by namantalaycha10** [comment]
trigger gitleaks

**Comment by NoahCallaway** [comment]
@namantalaycha10 - anything else you need from me? 
Can this be merged?

**Comment by bot2-harness** [comment]
This pull request has been automatically closed due to 30 days of inactivity. If you believe this was done in error, please feel free to reopen the PR or reach out to the BT team for further assistance. Thank you for your contributions!

**Pull request closed without merging**
