### PR TITLE
fix: multiple environment infrastructures

### PR DESCRIPTION
**Pull request by rssnyder**
## Describe your changes

Currently when getting infrastructures via the SDK we are using [GetInfrastructureList](https://github.com/harness/harness-go-sdk/blob/main/harness/nextgen/api_infrastructures.go#L472) which retrieves all of the infrastructure definitions for a particular environment, and then we just select the first option:

```go
readInfrastructure(d, &resp.Data.Content[0])
```

When a user has multiple infrastructures defined for a particular environment this is causing issues when trying to work with anything other than the first-configured infrastructure definition. The plan will always show changes that need to be made:

<details>

```shell
Terraform will perform the following actions:

  # harness_platform_infrastructure.dev_sa will be updated in-place
  ~ resource "harness_platform_infrastructure" "dev_sa" {
      ~ deployment_type = "ECS" -> "Kubernetes"
        id              = "lab"
      ~ name            = "lab" -> "sa"
        tags            = []
      ~ type            = "ECS" -> "KubernetesDirect"
      ~ yaml            = <<-EOT
            infrastructureDefinition:
          -   name: lab
          -   identifier: lab
          +   name: sa
          +   identifier: sa
              description: ""
              tags: {}
              orgIdentifier: default
              projectIdentifier: development
              environmentRef: dev
          -   deploymentType: ECS
          -   type: ECS
          +   deploymentType: Kubernetes
          +   type: KubernetesDirect
              spec:
          -     connectorRef: account.sales
          -     region: us-west-2
          -     cluster: riley-lab
          +     connectorRef: account.sagcp
          +     namespace: riley-dev-<+service.name>
          +     releaseName: release-<+INFRA_KEY>
              allowSimultaneousDeployments: false
        EOT
        # (4 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

harness_platform_infrastructure.dev_sa: Modifying... [id=lab]
harness_platform_infrastructure.dev_sa: Modifications complete after 0s [id=sa]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
➜  terraform git:(main) ✗ tf apply
<redacted refresh output>

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # harness_platform_infrastructure.dev_sa will be updated in-place
  ~ resource "harness_platform_infrastructure" "dev_sa" {
      ~ deployment_type = "ECS" -> "Kubernetes"
        id              = "lab"
      ~ name            = "lab" -> "sa"
        tags            = []
      ~ type            = "ECS" -> "KubernetesDirect"
      ~ yaml            = <<-EOT
            infrastructureDefinition:
          -   name: lab
          -   identifier: lab
          +   name: sa
          +   identifier: sa
              description: ""
              tags: {}
              orgIdentifier: default
              projectIdentifier: development
              environmentRef: dev
          -   deploymentType: ECS
          -   type: ECS
          +   deploymentType: Kubernetes
          +   type: KubernetesDirect
              spec:
          -     connectorRef: account.sales
          -     region: us-west-2
          -     cluster: riley-lab
          +     connectorRef: account.sagcp
          +     namespace: riley-dev-<+service.name>
          +     releaseName: release-<+INFRA_KEY>
              allowSimultaneousDeployments: false
        EOT
        # (4 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

harness_platform_infrastructure.dev_sa: Modifying... [id=lab]
harness_platform_infrastructure.dev_sa: Modifications complete after 0s [id=sa]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

</details>

To fix this I switched to using [GetInfrastructure](https://github.com/harness/harness-go-sdk/blob/main/harness/nextgen/api_infrastructures.go#L317) where we can target the specific infrastructure definition we are looking for.

I am not sure if the check for soft-delete is still needed here, so I decided to leave it in.

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

### CODE REVIEW

**Comment by rijajoo** [comment]
@rssnyder Changes look good. Can you help make your branch public so I can run some tests before merging this?

**Comment by rssnyder** [comment]
> @rssnyder Changes look good. Can you help make your branch public so I can run some tests before merging this?

My fork is public, can you be more specific in what you need me to do?

**Comment by rijajoo** [comment]
trigger build

**Comment by rijajoo** [comment]
trigger subcategoryfieldcheck

**Comment by rijajoo** [comment]
@rssnyder please help us resolve the build failing issue.

**Comment by rssnyder** [comment]
> @rssnyder please help us resolve the build failing issue.

fixed, built locally

**Comment by rijajoo** [comment]
trigger build

**Comment by rijajoo** [comment]
trigger subcategoryfieldcheck

**Comment by rssnyder** [comment]
done in https://github.com/harness/terraform-provider-harness/commit/8399ef5ef7ac24534447eb0c950b3aa71ea3a7ad

**Pull request closed without merging**
