### PR TITLE
Fixed Secret Text Bug and Increased Coverage

### PR DESCRIPTION
**Pull request by adiyaar24**
## Describe your changes
- Added Variable Value Support and Test Coverage
- Updated the Doc of Secret Text , as the value parameter is required but it was given as optional 

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

### CODE REVIEW

**Comment by adiyaar24** [comment]
trigger subcategoryfieldcheck

**Comment by adiyaar24** [comment]
trigger build

**Comment by rathodmeetsatish** [comment]
trigger subcategoryfieldcheck

**Review by rathodmeetsatish — DISMISSED** [review]
it optional in docs https://apidocs.harness.io/tag/Secrets#operation/postSecret!path=secret/spec/2/value&t=request please make it consistent either change apidocss as well or let it be optional in terraform

**Comment by adiyaar24** [comment]
> it optional in docs https://apidocs.harness.io/tag/Secrets#operation/postSecret!path=secret/spec/2/value&t=request please make it consistent either change apidocss as well or let it be optional in terraform

We cant make it optional , I will raise the ticket for the same to update in the API Docs

**Review by rijajoo — APPROVED** [review]

**Review by RajBaviskar — APPROVED** [review]

**Comment by RajBaviskar** [comment]
@adiyaar24 Please add changelog file

**Comment by adiyaar24** [comment]
> @adiyaar24 Please add changelog file

Updated the ChangeLog File

**Comment by RajBaviskar** [comment]
@adiyaar24 refer this PR for change log https://github.com/harness/terraform-provider-harness/commit/013043d75de7a411f010ae5dec478ad14e281400

undo your changes from CHANGELOG.md

**Pull request merged**
