### PR TITLE
fix: [PL-39175]: PR for adding delegate token resource

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`
- gitleaks: `trigger gitleaks`

### CODE REVIEW

**Comment by VikasMaddukuriHarness** [comment]
trigger build

**Comment by VikasMaddukuriHarness** [comment]
trigger build

**Comment by VikasMaddukuriHarness** [comment]
trigger build

**Review by adiyaar24 — APPROVED** [review]

**Comment by VikasMaddukuriHarness** [comment]
trigger gitleaks

**Comment by krishi0408** [comment]
trigger gitleaks

**Comment by krishi0408** [comment]
trigger gitleaks

**Comment by krishi0408** [comment]
trigger gitleaks

**Comment by krishi0408** [comment]
trigger gitleaks

**Comment by rathodmeetsatish** [comment]
trigger gitleaks

**Comment by krishi0408** [comment]
trigger gitleaks

**Comment by krishi0408** [comment]
trigger gitleaks

**Comment by krishi0408** [comment]
trigger gitleaks

**Comment by krishi0408** [comment]
trigger gitleaks

**Comment by krishi0408** [comment]
trigger gitleaks

**Pull request merged**
