### PR TITLE
Added Coverage for Variable Value Tests

### PR DESCRIPTION
**Pull request by adiyaar24**
## Describe your changes
- Added support for Testing Variable Value including the original & Updated Value
- Tested the Changes in QA , PROD

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

### CODE REVIEW

**Review by rijajoo — APPROVED** [review]

**Comment by adiyaar24** [comment]
trigger build

**Comment by adiyaar24** [comment]
trigger subcategoryfieldcheck

**Comment by adiyaar24** [comment]
trigger build

**Comment by adiyaar24** [comment]
trigger subcategoryfieldcheck

**Comment by adiyaar24** [comment]
trigger build

**Pull request merged**
