### PR TITLE
feat: [CDS-53980]: Tags added to AgentCluster

### PR DESCRIPTION
**Pull request by mankrit-singh**
## Describe your changes
Added support for optional Tags in Cluster.

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

### CODE REVIEW

**Review by vaibhav-si — DISMISSED** [review]

**Review by rathodmeetsatish — CHANGES_REQUESTED** [review]
Did the tests pass?

**Comment by mankrit-singh** [comment]
> Did the tests pass?

The existing test and new test both are giving 413 Response is too large. Looks like it would need some additional fixes unrelated to current changes. Will sync up with @manavjot-harness for that separately.

**Review by manavjot-harness — APPROVED** [review]

**Review by rathodmeetsatish — COMMENTED** [review]
tests are passing now right?

**Comment by mankrit-singh** [comment]
> tests are passing now right?
yes, when pointing to QA
There was a bug that got fixed. Once those change reach Prod, will merge this PR

**Review by rathodmeetsatish — COMMENTED** [review]
@mankrit-singh are the api changes backward compatible? will the users using older terraform version get error?

**Comment by mankrit-singh** [comment]
> @mankrit-singh are the api changes backward compatible? will the users using older terraform version get error?

Yes, we are adding an optional parameter in request and response bodies, this is backwards compatible.

**Pull request merged**
