### PR TITLE
Update platform_file_store_file.md

### PR DESCRIPTION
**Pull request by giuliocalzolari**
## Describe your changes

fix `platform_file_store_file` import command on docs

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`
- gitleaks: `trigger gitleaks`

### CODE REVIEW

**Comment by giuliocalzolari** [comment]
trigger build

**Comment by krishi0408** [comment]
trigger gitleaks

**Comment by giuliocalzolari** [comment]
trigger subcategoryfieldcheck

**Comment by giuliocalzolari** [comment]
trigger gitleaks

**Comment by giuliocalzolari** [comment]
@krishi0408 can you help me? for some reason, `gitleaks` failed... but I cannot see the logs

**Comment by bot2-harness** [comment]
This PR has been automatically closed due to inactivity.

**Pull request closed without merging**
