### PR TITLE
Added default option to AWS secrets manager

### PR DESCRIPTION
**Pull request by carsongee**
## Describe your changes
The provider for AWS is missing the Default option from the UI:
image

Ulan Bekishov recommended I give it a shot to add it myself

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

### CODE REVIEW

**Review by VikasMaddukuriHarness — APPROVED** [review]

**Review by tiwaritejas — APPROVED** [review]

**Comment by VikasMaddukuriHarness** [comment]
trigger build, subcategoryfieldcheck

**Review by rathodmeetsatish — CHANGES_REQUESTED** [review]
@VikasMaddukuriHarness @tiwaritejas there are changes in schema and examples so that will require doc change, also add changelog file and add tests to test new changes

**Comment by carsongee** [comment]
I have added to the existing test cases as well as an example to cover this new parameter. I'm happy to add additional test cases if this isn't sufficient. Additionally, I can try and update the auto-docs and schemas. I tried doing it locally, but it produced so many unrelated changes I decided it was better not to push them to be on the safe side. If you have guides or docs somewhere to update those, or you can give me instructions I'm happy to help move this forward. Thanks!

**Comment by rathodmeetsatish** [comment]
trigger build, subcategoryfieldcheck

**Review by rathodmeetsatish — APPROVED** [review]

**Comment by rathodmeetsatish** [comment]
trigger build, subcategoryfieldcheck

**Pull request merged**
