### PR TITLE
fix: [CDS-84847]: Pipeline resource update filters

### PR DESCRIPTION
**Pull request by manavjot-harness**
## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`
- gitleaks: `trigger gitleaks`

### CODE REVIEW

**Comment by rohitk-h** [comment]
*[`internal/service/platform/pipeline_filters/resource_pipeline_filters.go` line 89 at r1](https://reviewable.io/reviews/harness/terraform-provider-harness/778#-NkIiLHFEzSzkQSNu3PJ:-NkIiLHFEzSzkQSNu3PK:b-r3zegi) ([raw file](https://github.com/harness/terraform-provider-harness/blob/da3919fe2659b55bb5eb262245701bbe33a09205/internal/service/platform/pipeline_filters/resource_pipeline_filters.go#L89)):*
> ```Go
> 							Description: "Pipeline identifiers to filter on.",
> 							Type:        schema.TypeList,
> 							Optional:    true,
> ```

Is this optional?

**Comment by rohitk-h** [comment]
*[`internal/service/platform/pipeline_filters/resource_pipeline_filters.go` line 349 at r1](https://reviewable.io/reviews/harness/terraform-provider-harness/778#-NkIj2Yt-ZdpEqiZrBE0:-NkIj2Yt-ZdpEqiZrBE1:b-rzmq8a) ([raw file](https://github.com/harness/terraform-provider-harness/blob/da3919fe2659b55bb5eb262245701bbe33a09205/internal/service/platform/pipeline_filters/resource_pipeline_filters.go#L349)):*
> ```Go
> 		if attr := filterProperties["pipeline_tags"].([]interface{}); len(attr) > 0 {
> 			var hPipelineTags []nextgen.NgTag
> 			for _, v := range attr {
> ```

nit: can be extracted into common utility.

**Review by rohitk-h — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/harness/terraform-provider-harness/778)* status: all files reviewed, 2 unresolved discussions (waiting on @manavjot-harness)

**Review by rohitk-h — APPROVED** [review]

**Comment by manavjot-harness** [comment]
> _[`internal/service/platform/pipeline_filters/resource_pipeline_filters.go` line 89 at r1](https://reviewable.io/reviews/harness/terraform-provider-harness/778#-NkIiLHFEzSzkQSNu3PJ:-NkIiLHFEzSzkQSNu3PK:b-r3zegi) ([raw file](https://github.com/harness/terraform-provider-harness/blob/da3919fe2659b55bb5eb262245701bbe33a09205/internal/service/platform/pipeline_filters/resource_pipeline_filters.go#L89)):_
> 
> > ```go
> > 							Description: "Pipeline identifiers to filter on.",
> > 							Type:        schema.TypeList,
> > 							Optional:    true,
> > ```
> 
> Is this optional?

yes, this is a filter on the identifiers.

**Comment by manavjot-harness** [comment]
trigger gitleaks

**Review by rohitk-h — APPROVED** [review]

**Pull request merged**
