### PR TITLE
fix: service/infra/env import examples

### LINKED ISSUE #262: Resource Import Examples -  Incorrect
The documentation for importing resources is incorrect, seemingly across the board:

## Example
https://registry.terraform.io/providers/harness/harness/latest/docs/resources/platform_service

Example given is:
```
# Import using service id
terraform import harness_platform_service.example <service_id>
```

Should be

```
# Import using service id
terraform import harness_platform_service.example <org_id>/<project_id>/<service_id>
```

If you follow the listed version, you'll get panics due to trying to split the string (line 197 of helpers/schema.go). 

EDIT: The code for this function internally makes this more obvious - so it should make its way into the docs. 
image

### PR DESCRIPTION
**Pull request by rssnyder**
## Describe your changes

Correct import examples for services, infrastructure and environments. These resources are project specific.

closes #262

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

### CODE REVIEW

**Review by RajBaviskar — APPROVED** [review]

**Comment by rijajoo** [comment]
@rssnyder Changes look good. Can you help make your branch public so I can run some tests before merging this?

**Comment by rijajoo** [comment]
trigger build

**Comment by rijajoo** [comment]
trigger subcategoryfieldcheck

**Comment by rijajoo** [comment]
@rssnyder We need to regenerate docs once this is done. Can you please help make your branch public so we can do the same?

**Pull request closed without merging**
