### PR TITLE
fix: platform org docs use old resource names

### PR DESCRIPTION
**Pull request by rssnyder**
## Describe your changes

The documentation for harness_platform_organization uses the wrong resource names. This leads to errors when new users are copy/pasting from the documentation.

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

### CODE REVIEW

**Comment by rijajoo** [comment]
trigger build

**Comment by rijajoo** [comment]
trigger subcategoryfieldcheck

**Comment by rijajoo** [comment]
@rssnyder We need to regenerate docs once this is done. Can you please help make your branch public so we can do the same?

**Comment by rathodmeetsatish** [comment]
closing the pr as it has been updated in latest version https://registry.terraform.io/providers/harness/harness/latest/docs/resources/platform_organization

**Pull request closed without merging**
