### PR TITLE
fix: [CDS-59053]: make identifier optional

### PR DESCRIPTION
**Pull request by mteodor**
## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- Sub Category Field Check: `trigger subcategoryfieldcheck`

### CODE REVIEW

**Comment by mteodor** [comment]
trigger subcategoryfieldcheck

**Comment by mteodor** [comment]
trigger subcategoryfieldcheck

**Comment by mankrit-singh** [comment]
trigger subcategoryfieldcheck

**Comment by mteodor** [comment]
trigger subcategoryfieldcheck

**Comment by mankrit-singh** [comment]
trigger subcategoryfieldcheck

**Comment by mteodor** [comment]
trigger subcategoryfieldcheck

**Review by mankrit-singh — APPROVED** [review]

**Pull request merged**
